# Generated by Django 4.1.3 on 2023-02-01 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='id',
            field=models.BigIntegerField(editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
