# Generated by Django 4.1.3 on 2022-11-11 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_unit_price_product_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ['-create_at']},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-placed_at']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-last_update']},
        ),
        migrations.AlterField(
            model_name='product',
            name='promotions',
            field=models.ManyToManyField(to='store.promotion'),
        ),
    ]
