# Generated by Django 4.1.3 on 2023-02-03 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_customer_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-placed_at'], 'permissions': [('cancel_order', 'can cancel order')]},
        ),
    ]
