# Generated by Django 4.1.3 on 2023-02-09 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_order_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['user__first_name', 'user__last_name', 'birth_day', 'membership'], 'permissions': [('view_history', 'Can view history')]},
        ),
    ]
