# Generated by Django 4.1.3 on 2022-11-11 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tagitem',
            options={'ordering': ['object_id']},
        ),
    ]
